const existingDestinations = {
  "three-pools": {
    title: "三潭印月",
    subtitle: "一湖烟水 · 半卷江南",
    poem: ["水光潋滟晴方好", "山色空蒙雨亦奇"],
    paper: "#f5f2e8",
    fog: "#e9eadf",
    density: 0.0068,
    sky: "#fbf4de",
    ground: "#748579",
    sun: "#fff9e9",
    sunPower: 2.2,
    wash: [0.84, 0.85, 0.8],
    washAmount: 0.33,
    water: [0.61, 0.71, 0.68],
    view: { width: 43, height: 8, depth: -3, minimum: 64 },
  },
  leifeng: {
    title: "雷峰夕照",
    subtitle: "夕照山 · 暮色入湖",
    poem: ["湖上金波起", "塔影入烟霞"],
    asset: "leifeng.glb",
    paper: "#f5e9d4",
    fog: "#e8cfac",
    density: 0.0055,
    sky: "#ffe4b8",
    ground: "#8a8069",
    sun: "#ffd08a",
    sunPower: 2.5,
    wash: [0.91, 0.69, 0.44],
    washAmount: 0.45,
    water: [0.79, 0.66, 0.46],
    view: { width: 43, height: 8, depth: -3, minimum: 64 },
  },
  "broken-bridge": {
    title: "断桥残雪",
    subtitle: "白堤东端 · 雪霁初晴",
    poem: ["一桥分晴雪", "半湖入画来"],
    asset: "broken-bridge.glb",
    paper: "#eef2f2",
    fog: "#e1e9ec",
    density: 0.008,
    sky: "#ecf4ff",
    ground: "#7f939d",
    sun: "#f7fbff",
    sunPower: 1.5,
    wash: [0.82, 0.89, 0.93],
    washAmount: 0.64,
    water: [0.64, 0.74, 0.79],
    view: { width: 43, height: 6, depth: -3, minimum: 64 },
  },
  "nine-creeks": {
    title: "九溪烟树",
    subtitle: "山林茶径 · 溪声入林",
    poem: ["树深闻水响", "烟起见溪长"],
    asset: "nine-creeks.glb",
    backdrop: "jiuxi-backdrop.png",
    paper: "#eef1e5",
    fog: "#d7e2d1",
    density: 0.01,
    sky: "#f1f4dc",
    ground: "#54745c",
    sun: "#edf2cc",
    sunPower: 1.8,
    wash: [0.66, 0.76, 0.64],
    washAmount: 0.18,
    water: [0.4, 0.59, 0.49],
    view: { width: 31, height: 5, depth: -8, minimum: 50 },
  },
};

// Each entry describes a distinct authored model, its season and its viewing position.
const spring = existingDestinations["three-pools"];
const forest = existingDestinations["nine-creeks"];
const autumn = {
  ...spring,
  paper: "#f3e9d6",
  fog: "#e4d9ba",
  sky: "#fff0cd",
  water: [0.65, 0.68, 0.53],
  wash: [0.81, 0.75, 0.56],
  foliageTint: [1.1, 0.91, 0.56],
};
const twilight = {
  ...spring,
  paper: "#dfe6e7",
  fog: "#cad9df",
  sky: "#d8e8f5",
  sun: "#d9e6fa",
  sunPower: 1.1,
  water: [0.48, 0.62, 0.67],
  wash: [0.63, 0.74, 0.8],
  washAmount: 0.5,
};
const closeView = { width: 34, height: 6, depth: -6, minimum: 56 };
function landmark(id, title, subtitle, poem, palette = spring, details = {}) {
  const { asset, backdrop, ...appearance } = palette;
  return {
    ...appearance,
    density: appearance.density * 0.6,
    title,
    subtitle,
    poem,
    asset: `${id}.glb`,
    ...details,
    view: { ...(details.view || appearance.view), portraitWidth: 26 },
  };
}
export const destinations = {
  ...existingDestinations,
  "su-causeway": landmark(
    "su-causeway",
    "苏堤春晓",
    "六桥烟柳 · 桃色初醒",
    ["六桥连晓色", "桃柳夹春堤"],
    spring,
    { petals: "#eeb5ba" },
  ),
  "lotus-breeze": landmark(
    "lotus-breeze",
    "曲院风荷",
    "曲院回廊 · 荷香满湖",
    ["风翻千柄翠", "香过一亭凉"],
    spring,
    { water: [0.48, 0.64, 0.52], view: closeView },
  ),
  "autumn-moon": landmark(
    "autumn-moon",
    "平湖秋月",
    "孤山临水 · 月白风清",
    ["月落平湖镜", "风生一榭秋"],
    twilight,
    { moon: true, foliageTint: [1.08, 0.95, 0.64] },
  ),
  "fish-harbor": landmark(
    "fish-harbor",
    "花港观鱼",
    "花港红鱼 · 牡丹临池",
    ["红鱼穿浅碧", "花影落清池"],
    spring,
    { view: closeView },
  ),
  "willow-orioles": landmark(
    "willow-orioles",
    "柳浪闻莺",
    "长柳依岸 · 莺啼入春",
    ["柳丝牵绿浪", "莺语过长堤"],
    spring,
    { birds: true },
  ),
  "twin-peaks": landmark(
    "twin-peaks",
    "双峰插云",
    "南北双峰 · 云起千重",
    ["双峰穿晓雾", "一径入云深"],
    forest,
    { clouds: true, view: { width: 48, height: 13, depth: -18, minimum: 70 } },
  ),
  "nanping-bell": landmark(
    "nanping-bell",
    "南屏晚钟",
    "净慈暮色 · 钟越南屏",
    ["山静钟声远", "林深暮色浓"],
    autumn,
    {
      waterVisible: false,
      view: { width: 36, height: 7, depth: -4, minimum: 56 },
    },
  ),
  "bamboo-path": landmark(
    "bamboo-path",
    "云栖竹径",
    "云栖深处 · 竹影夹径",
    ["竹色分幽径", "风声到古亭"],
    forest,
    { backdrop: "jiuxi-backdrop.png", waterVisible: false, view: closeView },
  ),
  "osmanthus-rain": landmark(
    "osmanthus-rain",
    "满陇桂雨",
    "满觉陇 · 金粟落秋衣",
    ["桂雨随风细", "茶烟绕石阶"],
    autumn,
    { petals: "#eac77c", waterVisible: false, view: closeView },
  ),
  "tiger-spring": landmark(
    "tiger-spring",
    "虎跑梦泉",
    "大慈山麓 · 清泉出石",
    ["双虎留泉梦", "一泓洗客尘"],
    forest,
    { backdrop: "jiuxi-backdrop.png", waterVisible: false, view: closeView },
  ),
  "dragon-well": landmark(
    "dragon-well",
    "龙井问茶",
    "龙井茶村 · 一盏问春",
    ["茶垄随山转", "新芽带露香"],
    forest,
    { waterVisible: false, view: closeView },
  ),
  "wushan-wind": landmark(
    "wushan-wind",
    "吴山天风",
    "城隍高阁 · 江湖入望",
    ["天风来画阁", "城郭接湖山"],
    spring,
    {
      waterVisible: false,
      view: { width: 40, height: 13, depth: -5, minimum: 64 },
    },
  ),
  "ruan-islet": landmark(
    "ruan-islet",
    "阮墩环碧",
    "湖心小屿 · 碧水四围",
    ["一屿浮烟碧", "轻舟系柳阴"],
    spring,
  ),
  "yellow-dragon": landmark(
    "yellow-dragon",
    "黄龙吐翠",
    "黄龙洞 · 石壁泻清泉",
    ["龙泉飞翠壁", "竹色掩幽庭"],
    forest,
    { backdrop: "jiuxi-backdrop.png", waterVisible: false, view: closeView },
  ),
  "jade-emperor": landmark(
    "jade-emperor",
    "玉皇飞云",
    "玉皇山巅 · 福星云上",
    ["云行朱殿外", "山尽大江横"],
    spring,
    {
      clouds: true,
      waterVisible: false,
      view: { width: 40, height: 13, depth: -5, minimum: 64 },
    },
  ),
  "precious-stone": landmark(
    "precious-stone",
    "宝石流霞",
    "保俶塔下 · 赭石映霞",
    ["赭石留霞色", "孤塔倚湖光"],
    autumn,
    {
      waterVisible: false,
      view: { width: 38, height: 12, depth: -5, minimum: 64 },
    },
  ),
  lingyin: landmark(
    "lingyin",
    "灵隐禅踪",
    "灵隐古刹 · 飞来峰前",
    ["古刹藏深树", "苔痕入石龛"],
    forest,
    { backdrop: "jiuxi-backdrop.png", waterVisible: false },
  ),
  "liuhe-tide": landmark(
    "liuhe-tide",
    "六和听涛",
    "月轮山上 · 钱塘潮声",
    ["塔镇江天阔", "潮来万里声"],
    spring,
    { tide: true, view: { width: 43, height: 13, depth: -4, minimum: 68 } },
  ),
  "yue-fei": landmark(
    "yue-fei",
    "岳墓栖霞",
    "栖霞岭下 · 碧血丹心",
    ["松柏守忠骨", "栖霞映故碑"],
    autumn,
    { waterVisible: false },
  ),
  "lakeside-rain": landmark(
    "lakeside-rain",
    "湖滨晴雨",
    "湖滨长岸 · 雨色晴光",
    ["晴光浮远岫", "雨线入平湖"],
    spring,
    { rain: true, density: 0.0055, sky: "#e4e9e5", sunPower: 1.25 },
  ),
  "qian-king": landmark(
    "qian-king",
    "钱祠表忠",
    "钱王祠 · 三世五王",
    ["朱门临碧水", "古柏护祠堂"],
    spring,
    { waterVisible: false },
  ),
  wansong: landmark(
    "wansong",
    "万松书缘",
    "万松书院 · 松声书声",
    ["石磴通书院", "松风翻旧篇"],
    forest,
    { backdrop: "jiuxi-backdrop.png", waterVisible: false },
  ),
  "yang-causeway": landmark(
    "yang-causeway",
    "杨堤景行",
    "杨公堤 · 六桥寻幽",
    ["桥转芦汀外", "堤行水树间"],
    spring,
  ),
  santai: landmark(
    "santai",
    "三台云水",
    "三台山麓 · 芦汀云影",
    ["云过三台静", "芦深一水闲"],
    forest,
    { clouds: true },
  ),
  meijiawu: landmark(
    "meijiawu",
    "梅坞春早",
    "梅家坞 · 茶山春信",
    ["千畦新绿早", "几户白墙深"],
    forest,
    { waterVisible: false },
  ),
  beishan: landmark(
    "beishan",
    "北街梦寻",
    "北山街 · 湖畔旧时光",
    ["旧楼临水立", "树影过长街"],
    autumn,
  ),
};

export const collections = [
  {
    id: "classic",
    title: "旧十景",
    era: "南宋",
    description: "湖上四时，千年画境",
    ids: [
      "su-causeway",
      "lotus-breeze",
      "autumn-moon",
      "broken-bridge",
      "fish-harbor",
      "willow-orioles",
      "three-pools",
      "twin-peaks",
      "leifeng",
      "nanping-bell",
    ],
  },
  {
    id: "new",
    title: "新十景",
    era: "1985",
    description: "循山入林，问茶听泉",
    ids: [
      "bamboo-path",
      "osmanthus-rain",
      "tiger-spring",
      "dragon-well",
      "nine-creeks",
      "wushan-wind",
      "ruan-islet",
      "yellow-dragon",
      "jade-emperor",
      "precious-stone",
    ],
  },
  {
    id: "third",
    title: "新新十景",
    era: "2007 · 三评西湖十景",
    description: "人文山水，城湖相望",
    ids: [
      "lingyin",
      "liuhe-tide",
      "yue-fei",
      "lakeside-rain",
      "qian-king",
      "wansong",
      "yang-causeway",
      "santai",
      "meijiawu",
      "beishan",
    ],
  },
];
export const destinationOrder = collections.flatMap(
  (collection) => collection.ids,
);
export function destinationFromHash(hash) {
  const key = hash.replace(/^#/, "");
  return Object.hasOwn(destinations, key) ? key : "three-pools";
}
